### ISSUE TITLE
FTPO "left-middle" and "right-middle" arrows are misaligned

### ISSUE THREAD

**Issue by scurker** [dequelabs/pattern-library#122]
It seems like the arrow is only positioned correctly when there are _exactly_ three lines of text, otherwise it's misaligned.

_**One Line**_

![ftpo with one line text](https://user-images.githubusercontent.com/1062039/61472094-62fd8780-a949-11e9-8844-848fd225b809.png)

_**Two Lines**_

![ftpo with two lines text](https://user-images.githubusercontent.com/1062039/61472237-aa841380-a949-11e9-9cea-20c759830aad.png)

_**Three Lines**_

![ftpo with three lines text](https://user-images.githubusercontent.com/1062039/61472288-bf60a700-a949-11e9-8504-ecc041043c3f.png)

_**Four Lines**_

![ftpo with four line text](https://user-images.githubusercontent.com/1062039/61472369-e919ce00-a949-11e9-915c-0b6b5333563f.png)

_**Multi Lines**_

![ftpo with multiline text](https://user-images.githubusercontent.com/1062039/61472518-385ffe80-a94a-11e9-9b3c-eb0195b6f386.png)

**Comment by scurker** [comment]
It looks like we can fix this with just a few properties (assuming we zero out any other positioning properties):

```css
.dqpl-pointer-wrap .dqpl-arrow.right-middle {
    right: 0;
    top: 50%;
    transform: translateY(-50%) rotate(90deg) translateY(-76px);
}
```
