### ISSUE TITLE
remove border style applied to a [role="textbox"] within dqpl-select

### ISSUE THREAD

**Issue by schne324** [dequelabs/pattern-library#59]
```css
.dqpl-select [role="textbox"],
.dqpl-select [role="textbox"]:hover {
  border: 0;
}
```

...this is how cauldron-react implements the select
